services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oti_cep_api
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: curl -f http://db:5432
      interval: 1s
      timeout: 5s
      retries: 5
  backend:
    image: guikaua12/oti-software-desafio-cep:latest
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/oti_cep_api
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - JWT_SECRET
      - JWT_ISSUER
      - JWT_EXPIRE_DURATION

volumes:
  db_data:
    driver: local